import "server-only";

import { readFileSync } from "node:fs";
import path from "node:path";

import { validateProducts, type Product } from "@/lib/types";

/**
 * Build-time catalog loader. Reads the static `public/data/products.json`
 * (generated by `scripts/ingest.ts` — see spec 0002) directly from disk, never
 * over HTTP, so the whole catalog is available during SSG with no runtime
 * backend (RNF-02). The `server-only` import makes an accidental client import a
 * build error, keeping `node:fs` out of the browser bundle (RNF-03).
 */
const DATA_FILE = path.join(process.cwd(), "public", "data", "products.json");

let cache: Product[] | undefined;

function load(): Product[] {
  if (cache) return cache;
  const raw: unknown = JSON.parse(readFileSync(DATA_FILE, "utf-8"));
  const products = validateProducts(raw);
  cache = products.slice().sort((a, b) => a.nombre.localeCompare(b.nombre, "es"));
  return cache;
}

/** All products, sorted by name (es locale). */
export function getAllProducts(): Product[] {
  return load();
}

/** Single product by its `id`, or `undefined` if not found. */
export function getProductById(id: string): Product | undefined {
  return load().find((p) => p.id === id);
}

/** Distinct categories present in the catalog, sorted (es locale). Used by spec 0003. */
export function getCategories(): string[] {
  return [...new Set(load().map((p) => p.categoria))].sort((a, b) =>
    a.localeCompare(b, "es"),
  );
}
